"1": "Apple",
"2": "Ripened Apple",
"3": "Rotten Apple",
"4": "Grapes",
"5": "Ripened Grapes",
"6": "Rotten Grapes",
"7": "Quince",
"8": "Ripened Quince",
"9": "Rotten Quince",
"10": "Fig",
"11": "Ripened Fig",
"12": "Rotten Fig",
"13": "Raspberry",
"14": "Ripened Raspberry",
"15": "Rotten Raspberry",
"16": "Cranberry",
"17": "Ripened Cranberry",
"18": "Rotten Cranberry",
"19": "Blueberry",
"20": "Ripened Blueberry",
"21": "Rotten Blueberry",
"22": "Strawberry",
"23": "Ripened Strawberry",
"24": "Rotten Strawberry",
"25": "Scrag of Beast",
"26": "Aged Scrag of Beast",
"27": "Rotten Scrag of Beast",
"28": "Beast-Steak",
"29": "Aged Beast-Steak",
"30": "Rotten Beast-Steak",
"31": "Shorefish",
"32": "Aged Shorefish",
"33": "Rotten Shorefish",
"34": "Tideswimmer",
"35": "Aged Tideswimmer",
"36": "Rotten Tideswimmer",
"37": "Dried Fruit",
"38": "Fruit Roborant",
"39": "Fine Fruit Roborant",
"41": "Dried Meat",
"42": "Mincemeat Roborant",
"43": "Fine Mincemeat Roborant",
"45": "Dried Fish",
"46": "Roe Roborant",
"47": "Fine Roe Roborant",
"49": "Harspud",
"50": "Ripened Harspud",
"51": "Rotten Harspud",
"52": "Princess Harspud",
"53": "Ripened Princess Harspud",
"54": "Rotten Princess Harspud",
"55": "Dried Spud",
"56": "Harspud Roborant",
"57": "Fine Harspud Roborant",
"59": "Detoxifying Decoction",
"60": "Waking Powder",
"61": "Quenching Syrup",
"62": "Warming Salve",
"64": "Sobering Tonic",
"65": "Malleating Elixir",
"66": "Soothing Brew",
"67": "Panacea",
"68": "Parching Concoction",
"69": "Wicking Remedy",
"70": "Allheal Elixir",
"72": "Stability Extract",
"73": "Savagery Extract",
